spring:
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    # 默认情况下，AMQP端口为5672.端口15672显示Web UI（管理控制台）
    port: 5672
    username: admin
    password: 123456
    # rabbitmq默认是自动应答的，即消息传到接受者后不管接受者是否成功处理消息，队列会自动删除消息
    # 下面是开启手动应答
    publisher-confirms: true #支持发布确认
    publisher-returns: true  #支持发布返回
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
#        concurrency: 2 #指定最小的消费者数量（貌似没作用）
#        max-concurrency: 2 #指定最大的消费者数量（貌似没作用）
#  #          retry:
#  #            enabled: true #是否支持重试
